version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: api_test_bbdd
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: default
    volumes:
      - invoices-volume:/app/invoices

volumes:
  pgdata:
  m2-cache:
  invoices-volume:
